# Generated by Django 5.1.6 on 2025-04-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('processing_completed_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('TESTING', 'Under Testing'), ('COMPLETED', 'Testing Completed'), ('FAILED', 'Testing Failed')], default='TESTING', max_length=20)),
                ('error_type', models.CharField(choices=[('PROCESSING', 'Processing Error'), ('TESTING', 'Testing Error'), ('NONE', 'No Error')], default='NONE', max_length=20)),
                ('issues', models.TextField(blank=True, null=True)),
                ('testing_start_date', models.DateTimeField(auto_now_add=True)),
                ('testing_completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('road_id', models.CharField(max_length=100)),
                ('road_type', models.CharField(choices=[('MCW_LHS', 'MCW LHS'), ('MCW_RHS', 'MCW RHS'), ('SLL', 'SLL'), ('SRR', 'SRR'), ('IRR', 'IRR'), ('IRL', 'IRL')], max_length=10)),
                ('testing_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('rsa_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('xls_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('tester_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('testing_issues', models.TextField(blank=True, null=True)),
                ('rsa_issues', models.TextField(blank=True, null=True)),
                ('xls_issues', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='testing_dashboard.project')),
            ],
            options={
                'ordering': ['road_type', 'name'],
            },
        ),
    ]
